export const WORKOUT_SPLITS = [
  { value: "full-body", label: "Full Body" },
  { value: "upper-lower", label: "Upper/Lower" },
  { value: "ppl", label: "Push/Pull/Legs" },
  { value: "bro-split", label: "Bro Split" },
  { value: "arnold-split", label: "Arnold Split" },
  { value: "phul", label: "PHUL" },
  { value: "phat", label: "PHAT" },
  { value: "torso-limbs", label: "Torso/Limbs" },
  { value: "pplul", label: "PPLUL" },
];

export const BODY_PART_GROUPS = [
  { group: "Chest", sections: ["Upper", "Mid", "Lower", "Stretch"] },
  { group: "Back", sections: ["Lats", "Mid", "Lower", "Traps"] },
  { group: "Shoulders", sections: ["Front", "Side", "Rear", "Rotator Cuff"] },
  { group: "Arms", sections: ["Biceps", "Triceps", "Forearms"] },
  { group: "Legs", sections: ["Quads", "Hamstrings", "Glutes", "Calves", "Adductors", "Abductors"] },
  { group: "Core", sections: ["Upper", "Lower", "Obliques", "Serratus"] },
  { group: "Lower Back", sections: ["Erector Spinae"] },
  { group: "Neck", sections: ["Flexors", "Extensors"] },
  { group: "Tibialis", sections: ["Anterior"] },
];

export const EXERCISE_LIBRARY = [
  { id: "el-1", name: "Incline Barbell Bench Press", bodyPart: "Chest - Upper" },
  { id: "el-2", name: "Incline Dumbbell Press", bodyPart: "Chest - Upper" },
  { id: "el-3", name: "Incline Cable Fly", bodyPart: "Chest - Upper" },
  { id: "el-4", name: "Flat Barbell Bench Press", bodyPart: "Chest - Mid" },
  { id: "el-5", name: "Dumbbell Bench Press", bodyPart: "Chest - Mid" },
  { id: "el-6", name: "Machine Chest Press", bodyPart: "Chest - Mid" },
  { id: "el-7", name: "Cable Chest Press", bodyPart: "Chest - Mid" },
  { id: "el-8", name: "Decline Bench Press", bodyPart: "Chest - Lower" },
  { id: "el-9", name: "Decline Cable Fly", bodyPart: "Chest - Lower" },
  { id: "el-10", name: "Weighted Dips", bodyPart: "Chest - Lower" },
  { id: "el-11", name: "Push-ups", bodyPart: "Chest - Lower" },
  { id: "el-12", name: "Pec Fly", bodyPart: "Chest - Stretch" },
  { id: "el-13", name: "Dumbbell Pullover", bodyPart: "Chest - Stretch" },
  { id: "el-14", name: "Pull-ups", bodyPart: "Back - Lats" },
  { id: "el-15", name: "Chin-ups", bodyPart: "Back - Lats" },
  { id: "el-16", name: "Lat Pulldown", bodyPart: "Back - Lats" },
  { id: "el-17", name: "Wide Grip Pulldown", bodyPart: "Back - Lats" },
  { id: "el-18", name: "Neutral Grip Pulldown", bodyPart: "Back - Lats" },
  { id: "el-19", name: "Straight Arm Pulldown", bodyPart: "Back - Lats" },
  { id: "el-20", name: "Barbell Bent-over Row", bodyPart: "Back - Mid" },
  { id: "el-21", name: "Cable Row", bodyPart: "Back - Mid" },
  { id: "el-22", name: "Seated Machine Row", bodyPart: "Back - Mid" },
  { id: "el-23", name: "T-Bar Row", bodyPart: "Back - Mid" },
  { id: "el-24", name: "Chest Supported Row", bodyPart: "Back - Mid" },
  { id: "el-25", name: "Inverted Row", bodyPart: "Back - Mid" },
  { id: "el-26", name: "Single Arm Dumbbell Row", bodyPart: "Back - Mid" },
  { id: "el-27", name: "Meadows Row", bodyPart: "Back - Mid" },
  { id: "el-28", name: "Romanian Deadlift", bodyPart: "Back - Lower" },
  { id: "el-29", name: "Rack Pull", bodyPart: "Back - Lower" },
  { id: "el-30", name: "Hyperextension", bodyPart: "Back - Lower" },
  { id: "el-31", name: "Barbell Shrugs", bodyPart: "Back - Traps" },
  { id: "el-32", name: "Dumbbell Shrugs", bodyPart: "Back - Traps" },
  { id: "el-33", name: "Trap Bar Shrugs", bodyPart: "Back - Traps" },
  { id: "el-34", name: "Face Pull", bodyPart: "Back - Traps" },
  { id: "el-35", name: "Upright Row", bodyPart: "Back - Traps" },
  { id: "el-36", name: "Overhead Barbell Press", bodyPart: "Shoulders - Front" },
  { id: "el-37", name: "Dumbbell Shoulder Press", bodyPart: "Shoulders - Front" },
  { id: "el-38", name: "Arnold Press", bodyPart: "Shoulders - Front" },
  { id: "el-39", name: "Front Raise", bodyPart: "Shoulders - Front" },
  { id: "el-40", name: "Plate Front Raise", bodyPart: "Shoulders - Front" },
  { id: "el-41", name: "Lateral Raise", bodyPart: "Shoulders - Side" },
  { id: "el-42", name: "Cable Lateral Raise", bodyPart: "Shoulders - Side" },
  { id: "el-43", name: "Leaning Lateral Raise", bodyPart: "Shoulders - Side" },
  { id: "el-44", name: "Upright Row", bodyPart: "Shoulders - Side" },
  { id: "el-45", name: "Rear Delt Fly", bodyPart: "Shoulders - Rear" },
  { id: "el-46", name: "Reverse Pec Deck", bodyPart: "Shoulders - Rear" },
  { id: "el-47", name: "Face Pull", bodyPart: "Shoulders - Rear" },
  { id: "el-48", name: "External Rotation (Band/Cable)", bodyPart: "Shoulders - Rotator Cuff" },
  { id: "el-49", name: "Internal Rotation (Band/Cable)", bodyPart: "Shoulders - Rotator Cuff" },
  { id: "el-50", name: "Y Raise / Trap Raise", bodyPart: "Shoulders - Rotator Cuff" },
  { id: "el-51", name: "Scapular Pull-ups", bodyPart: "Shoulders - Rotator Cuff" },
  { id: "el-52", name: "Barbell Curl", bodyPart: "Arms - Biceps" },
  { id: "el-53", name: "EZ Bar Curl", bodyPart: "Arms - Biceps" },
  { id: "el-54", name: "Cable Curl", bodyPart: "Arms - Biceps" },
  { id: "el-55", name: "Bayesian Cable Curl", bodyPart: "Arms - Biceps" },
  { id: "el-56", name: "Hammer Curl", bodyPart: "Arms - Biceps" },
  { id: "el-57", name: "Incline Dumbbell Curl", bodyPart: "Arms - Biceps" },
  { id: "el-58", name: "Concentration Curl", bodyPart: "Arms - Biceps" },
  { id: "el-59", name: "Preacher Curl", bodyPart: "Arms - Biceps" },
  { id: "el-60", name: "Spider Curl", bodyPart: "Arms - Biceps" },
  { id: "el-61", name: "Drag Curl", bodyPart: "Arms - Biceps" },
  { id: "el-62", name: "Close Grip Bench Press", bodyPart: "Arms - Triceps" },
  { id: "el-63", name: "Skull Crushers", bodyPart: "Arms - Triceps" },
  { id: "el-64", name: "EZ Bar Skull Crushers", bodyPart: "Arms - Triceps" },
  { id: "el-65", name: "Overhead Cable Extension", bodyPart: "Arms - Triceps" },
  { id: "el-66", name: "Cable Pushdown", bodyPart: "Arms - Triceps" },
  { id: "el-67", name: "Rope Pushdown", bodyPart: "Arms - Triceps" },
  { id: "el-68", name: "Single Arm Pushdown", bodyPart: "Arms - Triceps" },
  { id: "el-69", name: "Cross Body Cable Extension", bodyPart: "Arms - Triceps" },
  { id: "el-70", name: "Overhead Dumbbell Extension", bodyPart: "Arms - Triceps" },
  { id: "el-71", name: "Overhead Barbell Extension", bodyPart: "Arms - Triceps" },
  { id: "el-72", name: "Bench Dips", bodyPart: "Arms - Triceps" },
  { id: "el-73", name: "Machine Dips", bodyPart: "Arms - Triceps" },
  { id: "el-74", name: "Tricep Kickback", bodyPart: "Arms - Triceps" },
  { id: "el-75", name: "Diamond Push-ups", bodyPart: "Arms - Triceps" },
  { id: "el-76", name: "Wrist Curl", bodyPart: "Arms - Forearms" },
  { id: "el-77", name: "Reverse Wrist Curl", bodyPart: "Arms - Forearms" },
  { id: "el-78", name: "Reverse Barbell Curl", bodyPart: "Arms - Forearms" },
  { id: "el-79", name: "Wrist Roller", bodyPart: "Arms - Forearms" },
  { id: "el-80", name: "Plate Pinch Hold", bodyPart: "Arms - Forearms" },
  { id: "el-81", name: "Farmer's Walk", bodyPart: "Arms - Forearms" },
  { id: "el-82", name: "Dead Hang", bodyPart: "Arms - Forearms" },
  { id: "el-83", name: "Barbell Squat", bodyPart: "Legs - Quads" },
  { id: "el-84", name: "Hack Squat", bodyPart: "Legs - Quads" },
  { id: "el-85", name: "Leg Press", bodyPart: "Legs - Quads" },
  { id: "el-86", name: "Leg Extension", bodyPart: "Legs - Quads" },
  { id: "el-87", name: "Smith Machine Squat", bodyPart: "Legs - Quads" },
  { id: "el-88", name: "Sissy Squat", bodyPart: "Legs - Quads" },
  { id: "el-89", name: "Step-ups", bodyPart: "Legs - Quads" },
  { id: "el-90", name: "Romanian Deadlift", bodyPart: "Legs - Hamstrings" },
  { id: "el-91", name: "Leg Curl", bodyPart: "Legs - Hamstrings" },
  { id: "el-92", name: "Nordic Curl", bodyPart: "Legs - Hamstrings" },
  { id: "el-93", name: "Deadlift", bodyPart: "Legs - Glutes" },
  { id: "el-94", name: "Hip Thrust", bodyPart: "Legs - Glutes" },
  { id: "el-95", name: "Bulgarian Split Squat", bodyPart: "Legs - Glutes" },
  { id: "el-96", name: "Walking Lunges", bodyPart: "Legs - Glutes" },
  { id: "el-97", name: "Cable Kickbacks", bodyPart: "Legs - Glutes" },
  { id: "el-98", name: "Standing Calf Raise", bodyPart: "Legs - Calves" },
  { id: "el-99", name: "Seated Calf Raise", bodyPart: "Legs - Calves" },
  { id: "el-100", name: "Donkey Calf Raise", bodyPart: "Legs - Calves" },
  { id: "el-101", name: "Adductor Machine", bodyPart: "Legs - Adductors" },
  { id: "el-102", name: "Abductor Machine", bodyPart: "Legs - Abductors" },
  { id: "el-103", name: "Cable Crunch", bodyPart: "Core - Upper" },
  { id: "el-104", name: "Weighted Crunch", bodyPart: "Core - Upper" },
  { id: "el-105", name: "Decline Sit-ups", bodyPart: "Core - Upper" },
  { id: "el-106", name: "Hanging Leg Raise", bodyPart: "Core - Lower" },
  { id: "el-107", name: "Hanging Knee Raise", bodyPart: "Core - Lower" },
  { id: "el-108", name: "Lying Leg Raise", bodyPart: "Core - Lower" },
  { id: "el-109", name: "Reverse Crunch", bodyPart: "Core - Lower" },
  { id: "el-110", name: "Russian Twist", bodyPart: "Core - Obliques" },
  { id: "el-111", name: "Side Plank", bodyPart: "Core - Obliques" },
  { id: "el-112", name: "Cable Woodchoppers", bodyPart: "Core - Obliques" },
  { id: "el-113", name: "Bicycle Crunch", bodyPart: "Core - Obliques" },
  { id: "el-114", name: "Ab Wheel Rollout", bodyPart: "Core - Serratus" },
  { id: "el-115", name: "Plank", bodyPart: "Core - Serratus" },
  { id: "el-116", name: "L-Sit Hold", bodyPart: "Core - Serratus" },
  { id: "el-117", name: "Scapular Push-ups", bodyPart: "Core - Serratus" },
  { id: "el-118", name: "Deadlift", bodyPart: "Lower Back - Erector Spinae" },
  { id: "el-119", name: "Romanian Deadlift", bodyPart: "Lower Back - Erector Spinae" },
  { id: "el-120", name: "Hyperextension", bodyPart: "Lower Back - Erector Spinae" },
  { id: "el-121", name: "Back Extension Machine", bodyPart: "Lower Back - Erector Spinae" },
  { id: "el-122", name: "Superman Hold", bodyPart: "Lower Back - Erector Spinae" },
  { id: "el-123", name: "Neck Curl", bodyPart: "Neck - Flexors" },
  { id: "el-124", name: "Neck Extension", bodyPart: "Neck - Extensors" },
  { id: "el-125", name: "Tibialis Raises", bodyPart: "Tibialis - Anterior" },
  { id: "el-126", name: "Resistance Band Dorsiflexion", bodyPart: "Tibialis - Anterior" },
];

export const PREDEFINED_WORKOUT_LIBRARY = [
  {
    id: "tpl-full-body-foundation",
    title: "Full Body Foundation",
    split: "full-body",
    level: "Beginner",
    frequency: "3 days / week",
    goal: "General Strength",
    summary: "A balanced whole-body template built around big compound lifts and simple progression.",
    focus: ["Technique", "Balanced growth", "Recovery-friendly"],
    schedule: ["Mon - Full Body A", "Wed - Full Body B", "Fri - Full Body C"],
    exercises: ["Back Squat", "Bench Press", "Romanian Deadlift", "Lat Pulldown", "Overhead Press", "Plank"],
  },
  {
    id: "tpl-full-body-strength",
    title: "Full Body Strength Builder",
    split: "full-body",
    level: "Intermediate",
    frequency: "3 days / week",
    goal: "Strength",
    summary: "A heavier full-body setup for lifters who want frequent practice on squat, press, and hinge patterns.",
    focus: ["Barbell strength", "Lower volume", "Progressive overload"],
    schedule: ["Mon - Heavy Full Body", "Wed - Volume Full Body", "Sat - Power Full Body"],
    exercises: ["Deadlift", "Front Squat", "Incline Press", "Chest-Supported Row", "Dips", "Hanging Leg Raise"],
  },
  {
    id: "tpl-upper-lower-lean-mass",
    title: "Upper Lower Lean Mass",
    split: "upper-lower",
    level: "Beginner",
    frequency: "4 days / week",
    goal: "Muscle Gain",
    summary: "An easy-to-recover four-day split that alternates upper and lower sessions for steady hypertrophy.",
    focus: ["Twice-weekly frequency", "Simple scheduling", "Joint-friendly"],
    schedule: ["Mon - Upper 1", "Tue - Lower 1", "Thu - Upper 2", "Fri - Lower 2"],
    exercises: ["Bench Press", "Cable Row", "Leg Press", "Romanian Deadlift", "Lateral Raise", "Calf Raise"],
  },
  {
    id: "tpl-ppl-hypertrophy",
    title: "PPL Hypertrophy Cycle",
    split: "ppl",
    level: "Intermediate",
    frequency: "6 days / week",
    goal: "Hypertrophy",
    summary: "A classic push, pull, legs rotation with enough weekly volume for chest, back, shoulders, and legs.",
    focus: ["High volume", "Muscle focus", "Repeatable weekly flow"],
    schedule: ["Mon - Push", "Tue - Pull", "Wed - Legs", "Thu - Push", "Fri - Pull", "Sat - Legs"],
    exercises: ["Incline Dumbbell Press", "Pull-Up", "Hack Squat", "Shoulder Press", "Barbell Row", "Leg Curl"],
  },
  {
    id: "tpl-bro-split-mass",
    title: "Bro Split Mass Builder",
    split: "bro-split",
    level: "Intermediate",
    frequency: "5 days / week",
    goal: "Bodybuilding",
    summary: "A body-part split that dedicates each training day to one major muscle group and arm work.",
    focus: ["Body-part emphasis", "Pump work", "Accessory variety"],
    schedule: ["Mon - Chest", "Tue - Back", "Wed - Shoulders", "Thu - Legs", "Fri - Arms"],
    exercises: ["Bench Press", "T-Bar Row", "Lateral Raise", "Barbell Squat", "Skull Crusher", "Hammer Curl"],
  },
  {
    id: "tpl-arnold-classic",
    title: "Arnold Classic Rotation",
    split: "arnold-split",
    level: "Advanced",
    frequency: "6 days / week",
    goal: "Upper-Body Growth",
    summary: "A high-frequency bodybuilding split built around chest-back, shoulders-arms, and legs twice weekly.",
    focus: ["High frequency", "Upper-body volume", "Advanced recovery demand"],
    schedule: [
      "Mon - Chest + Back",
      "Tue - Shoulders + Arms",
      "Wed - Legs",
      "Thu - Chest + Back",
      "Fri - Shoulders + Arms",
      "Sat - Legs",
    ],
    exercises: ["Incline Barbell Press", "Weighted Pull-Up", "Seated Press", "EZ-Bar Curl", "Leg Press", "Cable Fly"],
  },
  {
    id: "tpl-phul-power-size",
    title: "PHUL Power and Size",
    split: "phul",
    level: "Intermediate",
    frequency: "4 days / week",
    goal: "Strength + Hypertrophy",
    summary: "Power Hypertrophy Upper Lower combines two heavier strength days with two higher-volume growth sessions.",
    focus: ["Power days", "Hypertrophy days", "Hybrid progression"],
    schedule: ["Mon - Upper Power", "Tue - Lower Power", "Thu - Upper Hypertrophy", "Fri - Lower Hypertrophy"],
    exercises: ["Bench Press", "Bent-Over Row", "Back Squat", "Romanian Deadlift", "Dumbbell Press", "Leg Extension"],
  },
  {
    id: "tpl-phat-performance",
    title: "PHAT Performance Builder",
    split: "phat",
    level: "Advanced",
    frequency: "5 days / week",
    goal: "Powerbuilding",
    summary: "PHAT blends two power-focused sessions with three bodybuilding days for experienced lifters chasing size and strength.",
    focus: ["Powerbuilding", "High weekly workload", "Advanced planning"],
    schedule: ["Mon - Upper Power", "Tue - Lower Power", "Thu - Back + Shoulders", "Fri - Lower Body", "Sat - Chest + Arms"],
    exercises: ["Weighted Pull-Up", "Deadlift", "Paused Squat", "Incline Press", "Machine Row", "Cable Curl"],
  },
  {
    id: "tpl-torso-limbs-builder",
    title: "Torso Limbs Builder",
    split: "torso-limbs",
    level: "Intermediate",
    frequency: "4 days / week",
    goal: "Hypertrophy",
    summary: "A torso-limbs arrangement that keeps chest, back, and shoulders together while separating arms and legs.",
    focus: ["Even fatigue", "Arm emphasis", "Four-day balance"],
    schedule: ["Mon - Torso A", "Tue - Limbs A", "Thu - Torso B", "Fri - Limbs B"],
    exercises: ["Incline Press", "Chest-Supported Row", "Lateral Raise", "Hack Squat", "Leg Curl", "Cable Pushdown"],
  },
  {
    id: "tpl-pplul-hybrid",
    title: "PPLUL Hybrid Builder",
    split: "pplul",
    level: "Advanced",
    frequency: "5 days / week",
    goal: "Muscle + Strength",
    summary: "A hybrid split that starts with push, pull, legs, then finishes with targeted upper and lower sessions.",
    focus: ["Flexible five-day plan", "Extra upper-body frequency", "Strength-hypertrophy blend"],
    schedule: ["Mon - Push", "Tue - Pull", "Wed - Legs", "Fri - Upper", "Sat - Lower"],
    exercises: ["Incline Press", "Pull-Up", "Back Squat", "Seated Row", "Romanian Deadlift", "Lateral Raise"],
  },
];
